workflows:
  jarvis-mini-android:
    name: Jarvis Mini Android Build
    max_build_duration: 60

    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk

    scripts:
      - name: Build Debug APK
        script: ./gradlew clean assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
